version: 2
jobs:
  buildlinuxclang:
    docker:
      - image: ubuntu:bionic
    steps:
      - checkout
      - run:
          name: Build Linux with clang
          command: sh ci/linux.sh clang_build
      - store_artifacts:
          path: build/output/libNFDriver.zip
          destination: libNFDriver.zip
  buildlinuxgcc:
    docker:
      - image: ubuntu:bionic
    steps:
      - checkout
      - run:
          name: Build Linux with gcc
          command: sh ci/linux.sh gcc_build
      - store_artifacts:
          path: build/output/libNFDriver.zip
          destination: libNFDriver.zip
  buildlinuxandroid:
    docker:
      - image: ubuntu:bionic
    steps:
      - checkout
      - run:
          name: Build Android
          command: BUILD_ANDROID=1 sh ci/linux.sh build
      - store_artifacts:
          path: libNFDriver-androidx86.zip
          destination: libNFDriver-androidx86.zip
      - store_artifacts:
          path: libNFDriver-androidArm64.zip
          destination: libNFDriver-androidArm64.zip
  buildmac:
    macos:
      xcode: "11.5.0"
    steps:
      - checkout
      - run:
          name: Build OSX
          command: sh ci/osx.sh build
      - store_artifacts:
          path: build/output/libNFDriver.zip
          destination: libNFDriver.zip
  buildmacios:
    macos:
      xcode: "11.5.0"
    steps:
      - checkout
      - run:
          name: Build iOS
          command: BUILD_IOS=1 sh ci/osx.sh build
      - store_artifacts:
          path: build/output/libNFDriver.zip
          destination: libNFDriver.zip
  buildmacandroid:
    macos:
      xcode: "11.5.0"
    steps:
      - checkout
      - run: brew update
      - run: git submodule sync
      - run: git submodule update --init --recursive
      # Android NDK does not pass.
      - run: sudo spctl --master-disable
      - run:
          name: Build Android
          command: BUILD_ANDROID=1 sh ci/osx.sh build
      - store_artifacts:
          path: libNFDriver-androidx86.zip
          destination: libNFDriver-androidx86.zip
      - store_artifacts:
          path: libNFDriver-androidArm64.zip
          destination: libNFDriver-androidArm64.zip

workflows:
  version: 2
  build:
    jobs:
      - buildlinuxclang
      - buildlinuxgcc
      - buildlinuxandroid
      - buildmac
      - buildmacios
      - buildmacandroid
